# Generated by Django 6.0.6 on 2026-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pickup_info',
            field=models.TextField(blank=True),
        ),
    ]
