# Generated by Django 6.0.6 on 2026-06-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='pcs', max_length=50)),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('grains', 'Grains'), ('beverages', 'Beverages'), ('snacks', 'Snacks'), ('others', 'Others')], default='others', max_length=50)),
                ('storage_location', models.CharField(choices=[('fridge', 'Fridge'), ('freezer', 'Freezer'), ('pantry', 'Pantry'), ('counter', 'Counter')], default='pantry', max_length=50)),
                ('expiry_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_donated', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
    ]
