# Generated by Django 6.0.6 on 2026-08-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_fooditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
